### ISSUE TITLE
Cached images

### ISSUE THREAD

**Issue by meld-cp** [joethei/obsidian-plantuml#1]
Hi, this looks like a very useful plugin, thanks!

Do you have any plans to cache the results so the images aren't regenerated unless needed?

**Comment by joethei** [comment]
I actually have not thought about that.
Will definitely add it.

**Comment by joethei** [comment]
So after looking into this I noticed that obsidian already caches every result from code blocks,
this cache does not persist through restarts of the software.

I am not sure if adding a cache that is persistent would be a good idea as that would mean that all diagrams are saved to disk (even those that are deleted in source).
If the concern is data usage #6 would be a better fit, but that is not something that will happen soon.

**Comment by meld-cp** [comment]
That's pretty cool, I didn't know that Obsidian cached already,  I think that covers what I was concerned about.  Cheers!

**Comment by jlnrrg** [comment]
As the cache is not kept through a restart, I thought about circumventing the issue by using the [Come Down Plugin](https://github.com/mntno/obsidian-come-down). 

While the plugin does indeed save a backup image, when I restart the  app in airplane mode, plantuml tries to generate the image anew and is stuck there (as there's no connection). 

As this is an edge case of the combination of two plugins, I do not see the need for a fix, and just want to notify people who'll have the same idea.
