### ISSUE TITLE
New update is not rendering plantuml code blocks

### ISSUE THREAD

**Issue by spiritualgeek** [joethei/obsidian-plantuml#10]
No plantuml code blocks render anymore after the last update. Even in safe mode

**Comment by joethei** [comment]
What are your settings?
The diagram will be renderer after the debounce period after changes have been made. 

Is there something in the dev console(Ctrl+Shift+I)?
Also safe Mode disables all plugins.

**Comment by spiritualgeek** [comment]
I meant just with your plugin active. See log 
[obsidian.md-1630755746841.log](https://github.com/joethei/obsidian-plantuml/files/7109687/obsidian.md-1630755746841.log)
Thanks

**Comment by kcmvp** [comment]
I run into same issue

**Comment by joethei** [comment]
I am not sure if I fixed your issue as I cannot reproduce it reliably.
Please check if the newest update fixes this issue.

**Comment by erex** [comment]
Using the example codeblock from this repo (Bob/Alice/etc), no render with the most recent release 1.2.1
![image](https://user-images.githubusercontent.com/330744/132179564-d0177168-226e-42d8-b79a-f6f416399bef.png)
![image](https://user-images.githubusercontent.com/330744/132179635-8e9c2f88-b25a-41ef-a5e8-8e4285953e1d.png)

Windows 10 OS, running Obsidian 0.12.15

**Comment by maxtar** [comment]
I have the same problem.

**Comment by joethei** [comment]
As I cannot reproduce this issue at all (only run into it twice, but worked again after changing the puml code)
I need some more logs from the most recent release(1.2.3) from one of you.

**Comment by maxtar** [comment]
@joethei Where I can find them?

**Comment by joethei** [comment]
> @joethei Where I can find them?

Press Ctrl+Shift+I or on Mac go to View - > Open Developer Tools then copy the output on the console.
It might be helpful if you edit the diagram before copying the log.

**Comment by maxtar** [comment]
After editing diagram, it's painted...
Console:
![изображение](https://user-images.githubusercontent.com/10290098/132564528-59eb543b-9c75-4ecc-a350-e1ec0a9d5d3a.png)

**Comment by joethei** [comment]
Well at least it sometimes works…
From your screenshot it seems like you're not using the latest version of the plugin as I added some more messages to help me debug this.

**Comment by maxtar** [comment]
![изображение](https://user-images.githubusercontent.com/10290098/132664895-6adc4bca-1fab-4da2-aaec-0281d2746f2b.png)

**Comment by maxtar** [comment]
Yeap, I've checked again and got a new plugin update.
New logs: 
![изображение](https://user-images.githubusercontent.com/10290098/132665465-369d27d6-1e8b-4316-b464-6df33c4c30e5.png)

**Comment by maxtar** [comment]
Yeap, I've check update now and got the ne one.
New log:
![изображение](https://user-images.githubusercontent.com/10290098/132666102-c5bb0e90-a1ca-4a8d-8070-1d873aebf366.png)

**Comment by joethei** [comment]
Is it still not rendering diagrams or does it work now ?
Keep in mind that I just added debounce functionality(#8) so diagrams will not load instantly but with a delay(10 seconds by default)after you stopped editing the diagram to save on bandwidth.

**Comment by maxtar** [comment]
Not all diagrams painted. Only which I edited yesterday. I have many diagrams.
Could you do delay as parameter in plugin?

**Comment by joethei** [comment]
That delay is configurable in the plugin settings, called Debounce.

**Comment by erex** [comment]
Sample UML diagram now renders if I create a fresh note
![image](https://user-images.githubusercontent.com/330744/132671232-f1bc599f-c62b-42b6-9db1-8f3f351b0df9.png)
same code block does not render in note created last week
