### ISSUE TITLE
Gabage when send to local plantuml web

### ISSUE THREAD

**Issue by maxtar** [joethei/obsidian-plantuml#11]
I've run local plantuml server as described in [official documentation](https://plantuml.com/ru/picoweb).
I use `java -jar plantuml.jar -picoweb` command.
In plugin settings I set the server URL: http://localhost:8080.
I added to the note the following code:
```
```plantuml
@startuml
id1 -> id2
@enduml
```
After switching to read mode I've got the following....
![изображение](https://user-images.githubusercontent.com/10290098/132696320-1d76a9ab-0bbd-493c-8486-e84319370608.png)
Console:
![изображение](https://user-images.githubusercontent.com/10290098/132696481-7b8f78f6-dbca-4b45-8e85-dbe132da0201.png)

Browser shows the correct image:
![изображение](https://user-images.githubusercontent.com/10290098/132696636-d9102999-cc74-4c8d-95d8-980155d39f84.png)

**Comment by joethei** [comment]
Found the problem, the PicoWeb server does not support image maps(for making links clickable) and instead returns an image, which will be converted to this weird text.
Will be fixed in the next update.

**Comment by QAMichaelPeng** [comment]
Rolling back to 1.1.2 will temporarily fix the issue.
