### ISSUE TITLE
Markdown syntax is not working

### ISSUE THREAD

**Issue by avados** [joethei/obsidian-plantuml#14]
Hi, thanks for the plugin !
The markdown syntax from the [doc ](https://plantuml.com/mindmap-diagram) (with tabs) is not working:
```plantuml
@startmindmap
* root node
	* some first level node
		* second level node
		* another second level node
	* another first level node
@endmindmap
```
but using this syntax is ok:

```plantuml
 @startmindmap
* root node
** some first level node
*** second level node
**** another second level node
** another first level node
 @endmindmap
 ```
is it a correct behavior?

**Comment by joethei** [comment]
That does not look like correct behavior since the online server returns the correct result.
I am going to take a look in a few days.

**Comment by hmgqzx** [comment]
This problem still occurs on my environment. 
Obsidian Version 1.1.9 (Installer 0.15.9)
plugin version 1.6.6
