### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by kajdo** [joethei/obsidian-plantuml#15]
Hi,

I like the plugin a lot, but I'm missing a possibility to use the rendered diagram in a different program (f.e. mail) to share it.

I think the easiest possibility would be to include a button as overlay which when clicked copies the img into the clipboard.

another option would be to save the rendered img somewhere in the vault in full resolution to make it available on filesystem.

maybe I'm just missing something -- in that case, pls give me a hint ;)

well done - really extremely helpful! thx 100x

**Comment by joethei** [comment]
The [Copy Image and URL in Preview](https://github.com/NomarCub/obsidian-copy-url-in-preview) plugin as well as the [Image Toolkit](https://github.com/sissilab/obsidian-image-toolkit) plugin both include this functionality.
I am not going to reinvent the wheel for this, so please use one of these plugins.

**Comment by kajdo** [comment]
you're absolutely right .... didn't think about another plugin ... thx for the tipp!
