### ISSUE TITLE
Plugin fails to load in a new Obsidian installation

### ISSUE THREAD

**Issue by lalloni** [joethei/obsidian-plantuml#20]
### What happened?

I am a new Obsidian user, trying to using it on top of MacOS.

I installed obsidian-plantuml and every time I try to enable it I get an error from Obsidian:

> Failed to load plugin obsidian-plantuml

In the developer tools console I get:

```
app.js:1 Plugin failure: obsidian-plantuml TypeError: a is not a constructor
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
```

### Obsidian version

0.13.23

### Plugin version

1.5.0

### What distribution are you seeing the problem on?

Desktop

### Are you using a local `.jar` or a remote server

local .jar

### Relevant log output

```shell
app.js:1 Plugin failure: obsidian-plantuml TypeError: a is not a constructor
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
```

**Comment by lalloni** [comment]
I didn't had any chance to tell the plugin which plantuml.jar to use.

**Comment by joethei** [comment]
Whoops,
forgot how much chaos a single `^` can cause for older versions(I am on the latest insider)

**Comment by lalloni** [comment]
Confirming that it works perfectly now!
Thanks @joethei!
