### ISSUE TITLE
Does not render on Obsidian for Android and IOS

### ISSUE THREAD

**Issue by FreebeJan** [joethei/obsidian-plantuml#24]
First of all thank you for this plugin I, much enjoy it on the desktop.
On mobile devices however the diagrams are not rendered.

Steps to reproduce:
use the plantuml diagram from the example in the READMe

```plantuml
Bob -> Alice : hello
Alice -> Wonderland: hello
Wonderland -> next: hello
next -> Last: hello
Last -> next: hello
next -> Wonderland : hello
Wonderland -> Alice : hello
Alice -> Bob: hello
```
I tested on Mac Os, Linux and Windows, Android and IOS Apps, (all the latest version). Consistently its working on the Desktop Apps but not in the mobile ones. On mobile you are shown the plain plantuml markup snippet instead of the rendered diagram

**Comment by xuanyue202** [comment]
bug

**Comment by joethei** [comment]
I don't have this issue on my android device.
I am guessing there is something wrong with the way you installed the plugin.

You can take a look into the developer console to see the error:
> How to test plugins on Android
I think you need to have ADB on your computer installed (I always had that installed; if the following directions don't work without it, install it and activate it on your phone); on your android phone enable ADB (it's under developer settings [tap the build number three times to get these settings]); then connect the phone to your computer over USB; open chrome (or chromium based browser should also work) and type chrome://inspect in the browser. Open obsidian on your phone, then it should appear in the browser.
You will have the console and the inspector like you have for desktop Obsidian.

(Quoted from the Obsidian discord server)
