### ISSUE TITLE
"Inline" plant UML file rendering

### ISSUE THREAD

**Issue by jacob7395** [joethei/obsidian-plantuml#25]
When designing my system architecture using plantUML (just a quick thank you for making this extension), I would preferably store my UML in a separate file. I then use VS code while designing my diagrams.

Would it be possible to use Obisidiante inline (I'm not sure of the exact terminology) links and render the .pu files?

Hopefully, the image below demonstrates what I mean.
![image](https://user-images.githubusercontent.com/9060893/162614669-b3fe5ca8-839e-40dd-9568-6cdf52e0cda4.png)

**Comment by yordan-pavlov** [comment]
First, let me start by saying thanks for creating this PlantUML plugin for Obsidian.
Sadly, the embedding of .pu(ml) files no longer appears to work (with Obsidian v0.15.9)

I've tried both `.pu` and `.puml` files and both `![PlantUML diagram](diagram.puml)` and `![[diagram.puml]]` syntax for embedding but no diagram is rendered in the note.

This is using a local PlantUML server, running in docker. PlantUML diagrams in `plantuml` code-blocks are working fine. Hover preview (CTRL + hover) of linked PlantUML files ( `[PlantUML Diagram](diagram.puml)` ) is working as well. Only rendering of embedded diagrams doesn't seem to work.
