### ISSUE TITLE
Please add local cache file support

### ISSUE THREAD

**Issue by Edward0514** [joethei/obsidian-plantuml#33]
Hello, 
I use local jar to render the uml, if a file contains more than 20 blocks of plantuml, it will start 20 java processes at once, it will cause computer crash.
I think there is not need to real-time render the uml, instead generate uml in queue, and storage cache file in vault, when the plantuml block hash change, then regenerate the image and storage again.
Thank!

**Comment by joethei** [comment]
Oh, forgot to close this, it's a feature since a while ago
