### ISSUE TITLE
Option to always use SVG processor

### ISSUE THREAD

**Issue by huyz** [joethei/obsidian-plantuml#36]
**Is your feature request related to a problem? Please describe.**

I want to always have high-res SVG diagrams.  But I don't want to use `` ```plantuml-svg `` as that's not compatible with other Markdown processors (e.g., VS Code); I'd like to use `` ```plantuml `` as usual.

**Describe the solution you'd like**

Offer a setting that makes `plantuml` act as `plantuml-svg`. Maybe you could then offer `plantuml-png` for symmetry and completeness.

**Describe alternatives you've considered**

**Additional context**

I actually don't see a reason to use lower-res PNG. Is there an advantage that I'm missing?  Perhaps there's a good reason this is the default?

**Comment by joethei** [comment]
PNG is the default as it works for all diagram types, some types just don't work with SVG.

Will add it as an option.

**Comment by huyz** [comment]
Oh good to know. Is it possible to detect the diagram type and fall back to PNG when SVG isn't supported for a diagram type?

**Comment by joethei** [comment]
Not efficently I think

**Comment by joethei** [comment]
Looks like I forgot to close this issue, this feature has already been implemented a long time ago.
