### ISSUE TITLE
SVG works, PNG does not

### ISSUE THREAD

**Issue by boylesean** [joethei/obsidian-plantuml#38]
**Is your feature request related to a problem? Please describe.**

A diagram with some level of complexity does not render locally as PNG, though SVG seems to work.
All that is displayed is "Generating PlantUML diagram" and there is an error thrown on the console (see below).

**Describe the solution you'd like**

PNG would be nice b/c Image Toolkit allows me to copy an image to the system clipboard to paste into other apps.

**Describe alternatives you've considered**

As a workaround, I can put the code into a temporary file, then run plantuml.jar, which works but is klunky.

**Additional context**

There is some whining in the console wrt exceeding a quota.  I captured debug output from the console:

[obsidian.md-1661466216414.log](https://github.com/joethei/obsidian-plantuml/files/9428563/obsidian.md-1661466216414.log)

**Comment by joethei** [comment]
This should no longer happen, the issue was fixed a while ago, forgot to close this
