### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by Tykok** [joethei/obsidian-plantuml#40]
**Is your feature request related to a problem? Please describe.**
Actually when I try to export the Markdown notes into a PDF file, the PDF doesn't include the PlantUML diagram.

**Describe the solution you'd like**
I'd like the diagram can be include in the PDF file.

**Describe alternatives you've considered**
Maybe download the PNG image automatically when we export into PDF to include the diagram more easily.

**Additional context**

**Comment by prokofyevDmitry** [comment]
The workaround I found is that if you switch the note into `reading view` (in the right click menu of the document's tab)
![image](https://user-images.githubusercontent.com/8905771/210767616-ce7b2799-6923-4278-8b5e-a613eedcf80f.png)
 and then export it into PDF, the diagrams will be printed.  
![image](https://user-images.githubusercontent.com/8905771/210767671-3315d45c-d930-4a57-b535-cffbcd453276.png)

**Comment by Tykok** [comment]
Ok thanks. I'll use that way now.

Thank you ;)
