### ISSUE TITLE
Feature request: Option to export a rendered diagram locally

### ISSUE THREAD

**Issue by ohunter** [joethei/obsidian-plantuml#41]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to put multiple diagrams in my notes so that it is easier to understand what I'm writing about for myself. Sometimes I need to send the diagrams to others and I'd like to do so without sending the entire md file.

**Describe the solution you'd like**
The ability to export a rendered diagram using some sort of context menu.

**Describe alternatives you've considered**
Having plantuml installed locally is a hassle, especially when they are technically already rendered and stored in the document.

**Comment by jasal82** [comment]
+1

**Comment by bo-wu** [comment]
+1
rendering as png images could be export via other plugin. But as for svg, I didnot figure out a way to export svg as file
