### ISSUE TITLE
Compatibility with pandoc lua filters

### ISSUE THREAD

**Issue by UFOMelkor** [joethei/obsidian-plantuml#42]
The [pandoc lua filters](https://github.com/pandoc/lua-filters/tree/master/diagram-generator) allow passing additional attributes to the code block.

An example from their Readme (space at the end added by me for rendering in Github):

```
```{.plantuml caption="This is an image, created by **PlantUML**." width=50%}
@startuml
Alice -> Bob: Authentication Request Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request Alice <-- Bob: another Response
@enduml
`` `
```

As they use another identifier for the code block, the plugin currently ignores it.

It would be nice, if the plugin could at least render such code blocks as plantuml diagrams.

**Comment by joethei** [comment]
This is more of a feature request for core Obsidian.
Supporting this type of codeblock inside of this plugin would be quite a bit of additional work.
