### ISSUE TITLE
Using local jar leaks in Electron local storage

### ISSUE THREAD

**Issue by stonkie** [joethei/obsidian-plantuml#47]
Using the local JAR option, the images seem to be stored in cache in Electron's local storage.

However, they don't seem to get cleaned up which eventually leads to exceeded quota errors and being unable to render diagrams.

Reproduction is pretty simple. Just modify a diagram repeatedly and see the list grow here : 

![image](https://user-images.githubusercontent.com/4596002/214695624-4e7c1ce8-11f7-414d-8f55-2ffe4c02d9ee.png)

**Comment by stonkie** [comment]
Cleaning up the local storage gets it back on its feet for a little while.

**Comment by ReidWeb** [comment]
Able to reproduce, will attempt to produce a scenario you can step through in a git repo at some pt soon

At high level, reproduction steps match those outlined by stonkie - make a bunch of updates to a diagram.

Oddly i don't have anything in my local storage, had to outright clean the app storage
