### ISSUE TITLE
setting the default processor to svg is invalid

### ISSUE THREAD

**Issue by zhanglingde** [joethei/obsidian-plantuml#52]
I set the default processor to svg，but request plantuml server url is https://www.plantuml.com/plantuml/png/bPJBIiD0*****************

![Snipaste_2023-09-19_09-48-58](https://github.com/joethei/obsidian-plantuml/assets/51218642/153a72a6-2833-48ef-8611-e967b592410b)

**Comment by joethei** [comment]
That setting only applies when you include a `.pu/.puml` file in your note with `![[file.puml]]`.
If you want your diagram to use svg you need to use `plantuml-svg` as the language for your codeblock
