### ISSUE TITLE
Error in parameter list order for calling the local jar

### ISSUE THREAD

**Issue by KemalSoysal** [joethei/obsidian-plantuml#58]
After option -jar the local jar file location should be provided, instead the '-Djava.awt.headless=true' is appended.

https://github.com/joethei/obsidian-plantuml/blob/89cbfc6817c8c06180fdaa21d2d67e3f14e5ceb6/src/localProcessors.ts#L194

**Comment by joethei** [comment]
Huh, now I am confused how this could go by undetected for so long
