### ISSUE TITLE
Support local rendering

### ISSUE THREAD

**Issue by bpatram** [joethei/obsidian-plantuml#6]
It would be great if it was possible to render diagrams using a local version of Plantuml (in addition to cloud rendering). Some of my diagrams are proprietary and it would be preferred to avoid transferring that data over the wire to a thirdparty. Also, using a local version would more easily enable the inclusion of local files (#4).

Currently, I rely on a [VSCode plugin](https://github.com/qjebbs/vscode-plantuml) to handle my rendering outside of Obsidian. It offers both cloud and local rendering; so I wonder if it is possible to repurpose some of their code in this plugin.

**Comment by joethei** [comment]
Rendering locally would break compatibility with the API for the obsidian smartphone app.
You can host your own PlantUML server if you don't want anyone else to have access to your diagrams(links in the README).

I will leave this issue open, for if I do find a way around that limitation.

**Comment by hexawing** [comment]
As far as I know, some other one made it possible by using a local .jar file, which provided by plantUML offical site.

**Comment by joethei** [comment]
It would be possible to support local rendering with .jar files on desktop, but that would require importing some desktop only dependencies, which would break the plugin on mobile.
There is a way to import dependencies conditionaly, but that would require obsidian to update to at least support the ES2020 JS spec.
Which is something that would break compatibility with a few older devices.

As i would like to keep support for the mobile app, local rendering will not be possible for the forseeable future.

**Comment by loseblue** [comment]
> It would be possible to support local rendering with .jar files on desktop, but that would require importing some desktop only dependencies, which would break the plugin on mobile.
> There is a way to import dependencies conditionaly, but that would require obsidian to update to at least support the ES2020 JS spec.
> Which is something that would break compatibility with a few older devices.
> 
> As i would like to keep support for the mobile app, local rendering will not be possible for the forseeable future.

I think we can add a local path config, we support local rendering jar on desktop if local path is set, we use server url set if local path is null. 
And we us Server url on mobile directly.

**Comment by joethei** [comment]
> I think we can add a local path config, we support local rendering jar on desktop if local path is set, we use server url set if local path is null.
> And we us Server url on mobile directly.

Once we import the required libraries (namely `fs`) for accessing the .jar the plugin will no longer work on mobile.
(`fs` is not available on mobile and there is no alternative that would support the required operations on desktop)

The only way I can see this being implemented is conditional imports(requires ES2020, not happening soon, see: https://github.com/obsidianmd/obsidian-sample-plugin/issues/12) to only have `fs` imported on desktop.

**Comment by nsainaney** [comment]
I too would prefer local rendering primarily so I can create composable PlantUML diagrams (Issue #4). I ended up adding the following command to a package.json in the root.

```
"scripts": {
    "build": "plantuml -svg -Iplantuml.iuml -o ./_gen_media ./src/**/*.puml",
    ...
}
```

`plantuml.iuml` has universal items like theme etc.

I then use the `svg` files in Obsidian. It's an extra step but gets the job done until there's a reasonable solution for this.

I also have the following for hot-reloading:

```
   "develop": "chokidar \"./src/**/*.*\" -d 1000 -i \"**/_gen_media/**/*.*\" -c \"yarn build\"",
```

So I can run either `yarn build` or `yarn develop` to generate the `svg` files on the fly. This means however all my PlantUML is in `puml` files and not inline in the documents.

**Comment by jimkberry** [comment]
You can run the built-in picoweb server from a local PlantUML jar and use it as your server.
On a Win10 box I have a shortcut that has for a Target:  `C:\Apps\PlantUML\plantuml.jar -picoweb:8001`
and  `http://localhost:8001` at the plugin's URL setting. Seems to work fine (famous last words.)

See: https://plantuml.com/picoweb for more info.

**Comment by joethei** [comment]
You can now render your diagrams locally by installing the [Local Provider](https://github.com/joethei/obsidian-local-plantuml) plugin.

This issue will be closed once the plugin has been added to the community plugins.

**Comment by joethei** [comment]
Thanks to Licat`s superior knowledge of the way obsidian is build, this now build in, and no longer requires the local provider plugin.

**Comment by Musickiller** [comment]
> This issue will be closed once the plugin has been added to the community plugins.

I still can't see local render plugin in the community repo, and it's also marked as archived o_O

**Comment by joethei** [comment]
> I still can't see local render plugin in the community repo, and it's also marked as archived o_O

The provider plugin is no longer required.
See my previous message.

**Comment by hexawing** [comment]
> Thanks to Licat`s superior knowledge of the way obsidian is build, this now build in, and no longer requires the local provider plugin.

would you please to show me a demo? thanks!

**Comment by joethei** [comment]
> > Thanks to Licat`s superior knowledge of the way obsidian is build, this now build in, and no longer requires the local provider plugin.
> 
> would you please to show me a demo? thanks!

What do you mean by demo?
To have your diagrams rendered locally, just put in the path for the local `plantuml.jar` file into the settings for the plugin.

**Comment by joethei** [comment]
Are there any error messages in the console?
> To check for errors, first open the developer tools by pressing Ctrl-Shift-I on Windows/Linux or Cmd-Opt-I on macOS, and then go to the "Console" tab. If you want to save the error to a log file, you can right click on the error and choose "Save as...".

**Comment by Bashe** [comment]
> Are there any error messages in the console?
> 
> > To check for errors, first open the developer tools by pressing Ctrl-Shift-I on Windows/Linux or Cmd-Opt-I on macOS, and then go to the "Console" tab. If you want to save the error to a log file, you can 
[obsidian.md-1652359609702.log](https://github.com/joethei/obsidian-plantuml/files/8679149/obsidian.md-1652359609702.log)
right click on the error and choose "Save as...".

ha! Says that '-jar' is not recognized as an internal or external command ...blah-blah... 

attached the log file.

**Comment by Bashe** [comment]
I see 'java' in the options, but I can't modify it...

btw, in the terminal (both pwsh.exe and cmd.exe) running 'java -version' works just fine...

**Comment by hexawing** [comment]
> Okay, that sounds like `java` is not recognized as being available on the command line.
> 
> The latest plugin update added a option to configure where your java executable is located. (The `java.exe`) The default value should be fine for most cases, but in some(like your it seems) it fails.

![image](https://user-images.githubusercontent.com/230037/216261061-0b8d667b-10d6-4a9b-a57f-63acab73a5e6.png)
This is my settings. But it cannot render the graph.
Should I use "/" or "\" in the path?
or use "\ " for the space in "program files"?

**Comment by rabbitq0082** [comment]
> > Okay, that sounds like `java` is not recognized as being available on the command line.
> > The latest plugin update added a option to configure where your java executable is located. (The `java.exe`) The default value should be fine for most cases, but in some(like your it seems) it fails.
> 
> ![image](https://user-images.githubusercontent.com/230037/216261061-0b8d667b-10d6-4a9b-a57f-63acab73a5e6.png) This is my settings. But it cannot render the graph. Should I use "/" or "" in the path? or use "\ " for the space in "program files"?

I got the same problem with you

![image](https://user-images.githubusercontent.com/29980876/232417086-d23afcdd-150c-4a9c-9d6e-e97a7dda3f4b.png)
![image](https://user-images.githubusercontent.com/29980876/232417123-680f969d-8fce-4f27-a47d-59be9a1cab9a.png)
![image](https://user-images.githubusercontent.com/29980876/232417236-f578925e-b9b2-4185-8c71-546185929d49.png)
![image](https://user-images.githubusercontent.com/29980876/232417348-838977c2-0ef3-4f33-ace4-8aa797ecb52c.png)

**Comment by joeyst** [comment]
For anyone having this issue, make sure to put quotes around the file paths if they have any spaces. That got me for the Java path and I didn't get any console error for it; it just got stuck at "Generating PlantUML Diagram". 

Bad:   => C:\Program Files\Eclipse Adoptium\jdk-17.0.1.12-hotspot\bin\java.exe 
Good => "C:\Program Files\Eclipse Adoptium\jdk-17.0.1.12-hotspot\bin\java.exe"
Because 'Eclipse Adoptium' has a space. 

![image](https://github.com/joethei/obsidian-plantuml/assets/79038050/12fe6089-2041-4711-9b33-c2d3ee6acf42)
