### ISSUE TITLE
It is recommended that svg be used for rendering by default.

### ISSUE THREAD

**Issue by itachaaa** [joethei/obsidian-plantuml#67]
**Is your feature request related to a problem? Please describe.**

Currently, the PNG rendering is used by default. As a result, the rendering result may be blurred when the sizes are different.

**Describe the solution you'd like**

It is recommended that svg be used for rendering by default.
```JavaScript
    this.default = (source, el, ctx) => __async(this, null, function* () {
      yield this.svg(source, el, ctx);
    });
```

**Describe alternatives you've considered**

Provide configuration options for users to change the default renderer.

**Additional context**

Scaling problems may occur when the svg is used. If the image is too large, it cannot be displayed completely. It can be handled by certain css configuration, depending on your preference.
Force scale to current width：
```css
.markdown-preview-view svg {
    max-width: 150%;
    height: auto !important;
}
```

**Comment by joethei** [comment]
Not all diagram types are supported with SVG, some are only available when using PNG as the output format.
That's why PNG is the default.

**Comment by itachaaa** [comment]
Or is it possible to provide a switch or entry so that the user can choose what rendering to use?

**Comment by joethei** [comment]
Having that as a setting complicates the entire thing, since not all diagram types are supported when using SVG, I'd get bug reports about these.
If you want to have a diagram rendered as SVG, use `plantuml-svg` as the language.
