### ISSUE TITLE
Add debounce

### ISSUE THREAD

**Issue by alanvardy** [joethei/obsidian-plantuml#8]
Hello!

I have noticed that when I operate in split screen (one with the rendered PlantUML diagram and the other with the text) that when I make edits to the diagram the remote plantuml server will eventually quit responding for a short period of time. I think that this is because it is rightfully rate-limiting me.

Is it possible to add a debounce time that could be set in the settings? It would also save on data for people on expensive/limited connections.

I love this plugin and use it all across my vault to help conceptualize ideas, thanks for your work! :heart:

**Comment by joethei** [comment]
Good idea, going to implement it sometime next week. (I have some deadlines currently)

**Comment by alanvardy** [comment]
Thank you @joethei !

**Comment by joethei** [comment]
gona need to reopen this issue as my firt implementation was a bit flawed.

**Comment by joethei** [comment]
while working on a different [plugin](https://github.com/joethei/obsidian-link-favicon) I found a little trick to get this working, so this will finally be working.

During the debounce period you will not be able to see the image, so don't panic.
